web:
  build: .
  ports:
    - "80:80"
  links:
    - db
  volumes:
    - .:/var/www
    - ./public:/var/www/html
db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: raid123
    MYSQL_DATABASE: raid
  ports: 
    - "3306:3306"